### ISSUE TITLE
ext segfault: tests/015.php

### ISSUE THREAD

**Issue by glensc** [silexphp/Pimple#177]
```
[~/rpm/packages/BUILD.x86_64-linux/php55-ext-pimple-3.0.0] ➔ gdb --args php55 -dextension=modules/pimple.so tests/015.php
GNU gdb (GDB) 7.9-2 (PLD Linux)
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pld-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php55...Reading symbols from /usr/lib/debug/usr/bin/php55.debug...done.
done. 
(gdb) r
Starting program: /usr/bin/php55 -dextension=modules/pimple.so tests/015.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
object(Closure)#2 (0) {
}

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a25b49 in gc_zval_possible_root (zv=0x827560) at /usr/src/debug/php-5.5.24/Zend/zend_gc.c:143
143                     GC_ZOBJ_CHECK_POSSIBLE_ROOT(zv);
(gdb) bt
#0  0x00007ffff7a25b49 in gc_zval_possible_root (zv=0x827560) at /usr/src/debug/php-5.5.24/Zend/zend_gc.c:143
#1  0x00007ffff7a1276e in zend_hash_apply_deleter (ht=ht@entry=0x7ffff7dda428 <executor_globals+360>, p=0x8298c0)
    at /usr/src/debug/php-5.5.24/Zend/zend_hash.c:851
#2  0x00007ffff7a141f8 in zend_hash_graceful_reverse_destroy (ht=0x7ffff7dda428 <executor_globals+360>)
    at /usr/src/debug/php-5.5.24/Zend/zend_hash.c:889
#3  0x00007ffff79f6b06 in shutdown_executor () at /usr/src/debug/php-5.5.24/Zend/zend_execute_API.c:244
#4  0x00007ffff7a06223 in zend_deactivate () at /usr/src/debug/php-5.5.24/Zend/zend.c:1018
#5  0x00007ffff79a619f in php_request_shutdown (dummy=<optimized out>) at /usr/src/debug/php-5.5.24/main/main.c:1815
#6  0x000000000040590a in do_cli (argc=8549728, argv=0x8298c0) at /usr/src/debug/php-5.5.24/sapi/cli/php_cli.c:1181
#7  0x0000000000404e4a in main (argc=8549728, argv=0x8298c0) at /usr/src/debug/php-5.5.24/sapi/cli/php_cli.c:1382
(gdb) p zv
$4 = (zval *) 0x827560
(gdb) p *zv
$5 = {
  value = {
    lval = -1305158398551967969, 
    dval = -2.1627320582318623e+221, 
    str = {
      val = 0xede32559feb1371f <error: Cannot access memory at address 0xede32559feb1371f>, 
      len = -136491328
    }, 
    ht = 0xede32559feb1371f, 
    obj = {
      handle = 4273026847, 
      handlers = 0x7ffff7dd4ec0 <closure_handlers>
    }
  }, 
  refcount__gc = 4294967295, 
  type = 5 '\005', 
  is_ref__gc = 0 '\000'
}
(gdb) up
#1  0x00007ffff7a1276e in zend_hash_apply_deleter (ht=ht@entry=0x7ffff7dda428 <executor_globals+360>, p=0x8298c0)
    at /usr/src/debug/php-5.5.24/Zend/zend_hash.c:851
851                     ht->pDestructor(p->pData);
(gdb) p ht
$7 = (HashTable *) 0x7ffff7dda428 <executor_globals+360>
(gdb) p *ht
$8 = {
  nTableSize = 64, 
  nTableMask = 63, 
  nNumOfElements = 7, 
  nNextFreeElement = 0, 
  pInternalPointer = 0x81eb18, 
  pListHead = 0x81eb18, 
  pListTail = 0x8274e8, 
  arBuckets = 0x81e8e8, 
  pDestructor = 0x7ffff79f6460 <_zval_ptr_dtor>, 
  persistent = 0 '\000', 
  nApplyCount = 0 '\000', 
  bApplyProtection = 1 '\001'
}
(gdb) 
```

**Comment by glensc** [comment]
looks like the same test is failing here: #148

**Comment by stof** [comment]
@jpauli can you have a look at this ?
